### ISSUE TITLE
replace travis with actions

### ISSUE THREAD

**Issue by gr2m** [semantic-release/gitlab#168]
Part of https://github.com/semantic-release/semantic-release/issues/1692

### Todos

- [x] delete `.travis.yml`
- [x] create `.github/workflows/{test,release}.yml` (copy from https://github.com/semantic-release/npm/tree/master/.github/workflows)
- [x] remove `package-lock.json` from `.gitignore`
- [x] delete `.npmrc` and `.yarnrc`
- [x] README
	- [x] remove travis/codecov badges
	- [x] add actions badge instead (replace `REPO NAME HERE` ;): `[![Build Status](https://github.com/semantic-release/[REPO NAME HERE]/workflows/Test/badge.svg)](https://github.com/semantic-release/[REPO NAME HERE]/actions?query=workflow%3ATest+branch%3Amaster)`
- [x] create `package-json.lock`
- [x] add to package.json:
	- [x] `test:ci` script which doesn't run `lint` pre script
	- [x] renovate config 

		```
		  "renovate": {
		    "extends": [
		      "github>semantic-release/.github"
		    ]
		  }
		```
- [x] update branch protection: remove required status by Travis and Codecov, add required status for "test" (wait for first build of PR)
